export const facilities = [
  { name: "Free Wi-Fi", icon: "bi-wifi" },
  { name: "Air Conditioning", icon: "bi-snow" },
  { name: "Hot Water", icon: "bi-droplet" },
  { name: "TV", icon: "bi-tv" },
  { name: "Security Cameras", icon: "bi-camera-video" },
  { name: "Parking", icon: "bi-car-front" },
  { name: "Breakfast Included", icon: "bi-cup-hot" },
  { name: "Restaurant Onsite", icon: "bi-shop" },
  { name: "Room Service", icon: "bi-bell" },
  { name: "Swimming Pool", icon: "bi-water" },
  { name: "Pet Allowed", icon: "bi-emoji-smile" },
  { name: "Wheelchair Accessible", icon: "bi-person-wheelchair" },
  { name: "Fire Safety", icon: "bi-fire" },
];
